### ISSUE TITLE
Add support to Python 3.11 on PyPI

### ISSUE THREAD

**Issue by nunesgh** [chatziko/libqif#5]
Hi!

Python 3.11 is already stable, but the `qif` package on PyPI [does not support it yet](https://pypi.org/project/qif/#files).

When trying to install the package via `pip install qif` on a Python 3.11 installation, the following errors are reported:
> ERROR: Could not find a version that satisfies the requirement qif (from versions: none)
> ERROR: No matching distribution found for qif

Thank you!

**Comment by chatziko** [comment]
Just released a new version which works with python 3.11.
